### ISSUE TITLE
broken imports still

### ISSUE THREAD

**Issue by piotr25691** [nextcord/nextcord#65]
### Summary

dislash.py, DiscordUtils and other libraries adding on to discord.py do not work with nextcord

### Reproduction Steps

I just installed the original latest version of those packages form PyPI and the error occurred

### Expected Results

The modules should've imported correctly and the bots using it should have started with no problems.

### Actual Results

This error occurred:
```py
File "/home/container/process-aeon/main.py", line 8, in <module>
    from dislash import *
  File "/home/container/.local/lib/python3.8/site-packages/dislash/__init__.py", line 4, in <module>
    from .interactions import *
  File "/home/container/.local/lib/python3.8/site-packages/dislash/interactions/__init__.py", line 1, in <module>
    from .interaction import *
  File "/home/container/.local/lib/python3.8/site-packages/dislash/interactions/interaction.py", line 5, in <module>
    from discord.http import Route
  File "/home/container/.local/lib/python3.8/site-packages/discord/http.py", line 53, in <module>
    from . import __version__, utils
ImportError: cannot import name '__version__' from 'discord' (/home/container/.local/lib/python3.8/site-packages/discord/__init__.py)
```

### Intents

Intents.members

### System Information

```
- Python v3.8.10-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a1
- aiohttp v3.7.3
- system info: Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### Additional Context

I might have filed a duplicate issue, but please review this issue anyways, the latest commit fixing this issue is broken.

**Comment by piotr25691** [comment]
#67 doesn't work please fix

**Comment by TAG-Epic** [comment]
@piotr25691 Should be fixed in #68

**Comment by piotr25691** [comment]
still broken, maybe a version bump would help?
pip doesnt seem to acknowledge a new version so it keeps the old version and thus is still broken

**Comment by TAG-Epic** [comment]
> still broken, maybe a version bump would help?
> pip doesnt seem to acknowledge a new version so it keeps the old version and thus is still broken

Are you installing from master or from pypi?

**Comment by ooliver1** [comment]
> still broken, maybe a version bump would help?
> pip doesnt seem to acknowledge a new version so it keeps the old version and thus is still broken

try uninstalling then pip installing git+https://github.com/nextcord/nextcord

**Comment by piotr25691** [comment]
> > still broken, maybe a version bump would help?
> > pip doesnt seem to acknowledge a new version so it keeps the old version and thus is still broken
> 
> Are you installing from master or from pypi?

i tried installing from master and i even tried directly specifying the commit,
didnt work
